### ISSUE TITLE
Touch panel type interaction

### ISSUE THREAD

**Issue by koraybilgi** [Goddchen/flutter-vnc#16]
Hi @Goddchen ,

First of all, thanks for the effort you put into this project. I'm sure it's definitely a life saver for many. It definitely did for us.

I am unfamiliar with the Dart and Flutter. So I'm sorry in advance if I express myself wrong.

I need to create a **touch panel type interaction** that some other vnc clients have. In other words, when a touch event made in the app screen, I want to send a pointer event to the vnc server with the coordinates of that click directly.

I wonder if it's possible to achieve this by changing the calculation of the x and y properties sent with the `RemoteFrameBufferIsolateSendMessage.pointerEvent` in [remote_frame_buffer_gesture_detector.dart](https://github.com/Goddchen/flutter-rfb/blob/b7aa339c5534b54a63674df64b26dfb86414b815/lib/src/remote_frame_buffer_gesture_detector.dart) ?

Thanks.

**Comment by Goddchen** [comment]
Hi!
I'm not exactly sure what would need to be customized at all to achieve this. What you describe sounds to me like simply connecting to a running VNC server and controlling it. Did I miss something?

**Comment by koraybilgi** [comment]
I'm sorry, It's totally my fault. I thought a behavior I encountered in the simulator was a general problem :speak_no_evil: I'm closing the issue. Thank you for your time though.
