### ISSUE TITLE
SSH tunnel to VNC

### ISSUE THREAD

**Issue by Gabriel-Hobart** [Goddchen/flutter-vnc#20]
Could this package be used to connect to a VNC through a SSH tunnel? I've been trying the whole day to do it, but I haven't managed to get a successful connection.

**Comment by Goddchen** [comment]
I don't how the type of network connection could interfere the functionality. I haven't done it yet via SSH, but it should work. Can you describe in more detail what exactly is not working? Do other services work over the SSH connection? Maybe you misconfigured the ports that are tunneled or something like that?

**Comment by Gabriel-Hobart** [comment]
It's my first time implementing an SSH tunnel in Flutter, so it might be that I'm not implementing it correctly. I have managed to establish an SSH connection to my other device through the dartssh2 package. I'm just making sure it is possible so I can keep up hopes to find a solution.

**Comment by Goddchen** [comment]
Aha, I see. Didn't know about this package before, interesting.

"Forwarding: Supports local forwarding and remote forwarding."
This is the feature that you are looking for.

Are you sure that you are forwarding the correct port(s)?

**Comment by Gabriel-Hobart** [comment]
I believe I am working with the right ports.

```
class _MyHomePageState extends State<MyHomePage> {
  SSHClient? client;
  SSHSocket? _socket;

  bool authenticated = false;
  bool forwarded = false;

  @override
  void initState() {
    super.initState();

    sshConnect();
  }

  sshConnect() async {
    _socket = await SSHSocket.connect('TargetIP', 22);
    client = SSHClient(_socket!,
        username: 'user',
        onPasswordRequest: () => 'password',
        onAuthenticated: () => setState(() => authenticated = true));

    await client!.authenticated;
    final serverSocket = await ServerSocket.bind('localhost', 5900);

  print('Listening on ${serverSocket.address.address}:${serverSocket.port}');

  await for (final socket in serverSocket) {
    final forward = await client.forwardLocal('TargetIP', 22);
    forward.stream.cast<List<int>>().pipe(socket);
    socket.cast<List<int>>().pipe(forward.sink);
  }

  client.close();
  await client.done;
    setState(() => forwarded = true);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Theme.of(context).colorScheme.inversePrimary,
        title: Text(widget.title),
      ),
      body: Center(
        child: !(authenticated && forwarded)
            ? const Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  Text("Connecting to SSH client..."),
                  CircularProgressIndicator()
                ],
              )
            : InteractiveViewer(
                constrained: true,
                maxScale: 10,
                child: RemoteFrameBufferWidget(
                  hostName: 'localhost',
                  port: 5900,
                  onError: (final Object error) {
                    ScaffoldMessenger.of(context).showSnackBar(
                      SnackBar(
                        duration: const Duration(days: 1),
                        content: Text('Error: $error'),
                      ),
                    );
                  },
                  password: null,
                ),
              ),
      ),
    );
  }
}
```

**Comment by Goddchen** [comment]
Sorry, aren't you confusing the 2 examples in the package's readme? Can you explain your scenario again? You are running on VNC server on your remote server and on which port? And you want to connect to this remote server via SSH and route the remote server's VNC port to a local port, to which you can then connect. Am I right?

**Comment by Gabriel-Hobart** [comment]
Alright, let me go into a little bit more detail.
First, let me preface this by letting you know that I'm currently reverse-engineering an old java application which connects to a VNC server on a Linux device. So, if something doesn't seem right, it might be because of my lack of understanding. This being said, this is what I've found out:

1. The Linux device has a VNC server running, connecting to the port 5900 lets you see the main screen of the device.
2. It uses the RFB protocol.
3. The connection goes through an SSH Tunnel through port 22, this is password and user protected.
4. The old app seems to be using Local Port Forwarding for the connection.
5. The old app uses the JSCH package to manage the SSH connection.
6. In order to connect to the Linux device you need to input a host name (Generally `localhost`), a port number (5900), an ssh user name, ssh password, ssh host name (the device's IP), and ssh port (22).
7. After setting up the SSH port forwarding with the method [setPortForwardingL](https://epaul.github.io/jsch-documentation/javadoc/com/jcraft/jsch/Session.html#setPortForwardingL-int-java.lang.String-int-)(int lport, [String](http://download.oracle.com/javase/6/docs/api/java/lang/String.html?is-external=true) host, int rport) it retrieves a port to create a socket in `localhost`.

**Comment by Gabriel-Hobart** [comment]
Alright, I've confirmed that the flutter_rfb **DOES** work if you create a tunnel adequately. My issue is that I'm having trouble creating the tunnel with the dartssh2 so I used a Java app to create the tunnel instead, and the RemoteFrameBufferWidget connected successfully.

**Comment by Goddchen** [comment]
Thanks @Gabriel-Hobart , that was my guess as well. Glad to hear that it is now working for you.

**Comment by Gabriel-Hobart** [comment]
Yeah, now I have to find a way to create an adequate SSH tunnel from flutter

**Comment by Goddchen** [comment]
I'd guess that the package you have been using will work fine if configured correctly.
