### ISSUE TITLE
stack corruption detected

### ISSUE THREAD

**Issue by SteMMo33** [Goddchen/flutter-vnc#25]
Hi, I'm testing the package simply with the example test on my Samsung A510F.
I only changed the hostName parameter to point the UltraVNC server on my laptop.
After a couple of seconds The app crashes.
this is the debug log:

I/flutter (14271): INFO RemoteFrameBufferWidget: Spawning new isolate for RFB client
I/flutter (14271): INFO RemoteFrameBufferClient: < RemoteFrameBufferProtocolVersionHandshakeMessage(version: RemoteFrameBufferProtocolVersion.v3_8())
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferProtocolVersionHandshakeMessage(version: RemoteFrameBufferProtocolVersion.v3_8())
I/flutter (14271): INFO RemoteFrameBufferClient: < numberOfSecurityTypes=3
I/flutter (14271): INFO RemoteFrameBufferClient: < RemoteFrameBufferSecurityHandshakeMessage(securityTypes: (RemoteFrameBufferSecurityType.invalid(), RemoteFrameBufferSecurityType.invalid(), RemoteFrameBufferSecurityType.vncAuthentication()))
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferSecurityType.vncAuthentication()
I/flutter (14271): INFO RemoteFrameBufferClient: < Security challenge
I/flutter (14271): INFO RemoteFrameBufferClient: > Security challenge response
I/flutter (14271): INFO RemoteFrameBufferClient: < RemoteFrameBufferSecurityResultHandshakeMessage(success: true)
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferClientInitMessage(sharedFlag: true)
I/flutter (14271): INFO RemoteFrameBufferClient: < RemoteFrameBufferServerInitMessage(frameBufferHeightInPixels: 1080, frameBufferWidthInPixels: 1920, name: nd045 ( 192.168.5.86 ) - application mode, serverPixelFormat: RemoteFrameBufferPixelFormat(bitsPerPixel: 32, depth: 24, bigEndian: false, trueColor: true, redMax: 255, greenMax: 255, blueMax: 255, redShift: 16, greenShift: 8, blueShift: 0))
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferSetPixelFormatMessage(pixelFormat: RemoteFrameBufferPixelFormat(bitsPerPixel: 32, depth: 24, bigEndian: false, trueColor: true, redMax: 255, greenMax: 255, blueMax: 255, redShift: 16, greenShift: 8, blueShift: 0))
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferSetEncodingsMessage(encodingTypes: [RemoteFrameBufferEncodingType.copyRect(), RemoteFrameBufferEncodingType.raw()])
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferFrameBufferUpdateRequestMessage(height: 1080, incremental: true, width: 1920, x: 0, y: 0)
I/flutter (14271): INFO RemoteFrameBufferClient: < messageType: 0
I/flutter (14271): FINE RemoteFrameBufferClient: < 1 rectangles
I/flutter (14271): FINE RemoteFrameBufferClient: < RemoteFrameBufferFrameBufferUpdateMessageRectangleHeader(encodingType: RemoteFrameBufferEncodingType.raw(), height: 1080, width: 1920, x: 0, y: 0)
I/flutter (14271): INFO RemoteFrameBufferClient: < update rectangles: {RemoteFrameBufferEncodingType.raw(): 1}
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferFrameBufferUpdateRequestMessage(height: 1080, incremental: true, width: 1920, x: 0, y: 0)
I/flutter (14271): INFO RemoteFrameBufferClient: > RemoteFrameBufferClientCutTextMessage(text: https://www.ilpost.it/2024/11/19/baseball-guanto-misurare-tocco-forza-lanci/)
I/flutter (14271): INFO RemoteFrameBufferClient: < messageType: 0
I/flutter (14271): FINE RemoteFrameBufferClient: < 5 rectangles
I/flutter (14271): FINE RemoteFrameBufferClient: < RemoteFrameBufferFrameBufferUpdateMessageRectangleHeader(encodingType: RemoteFrameBufferEncodingType.raw(), height: 128, width: 1792, x: 64, y: 768)
I/flutter (14271): FINE RemoteFrameBufferClient: < RemoteFrameBufferFrameBufferUpdateMessageRectangleHeader(encodingType: RemoteFrameBufferEncodingType.raw(), height: 64, width: 128, x: 192, y: 896)
I/flutter (14271): FINE RemoteFrameBufferClient: < RemoteFrameBufferFrameBufferUpdateMessageRectangleHeader(encodingType: RemoteFrameBufferEncodingType.raw(), height: 64, width: 1280, x: 448, y: 896)
I/flutter (14271): FINE RemoteFrameBufferClient: < RemoteFrameBufferFrameBufferUpdateMessageRectangleHeader(encodingType: RemoteFrameBufferEncodingType.raw(), height: 64, width: 64, x: 1856, y: 896)
I/flutter (14271): FINE RemoteFrameBufferClient: < RemoteFrameBufferFrameBufferUpdateMessageRectangleHeader(encodingType: RemoteFrameBufferEncodingType.raw(), height: 64, width: 832, x: 576, y: 960)
I/flutter (14271): INFO RemoteFrameBufferClient: < update rectangles: {RemoteFrameBufferEncodingType.raw(): 5}
F/libc    (14271): stack corruption detected
F/libc    (14271): Fatal signal 6 (SIGABRT), code -6 in tid 14271 (m.stemmo.my_vnc)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/a5xeltexx/a5xelte:7.0/NRD90M/A510FXXS8CTI7:user/release-keys'
Revision: '4'
ABI: 'arm'
pid: 14271, tid: 14271, name: m.stemmo.my_vnc  >>>  <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: 'stack corruption detected'
    r0 00000000  r1 000037bf  r2 00000006  r3 00000008
    r4 f49eb58c  r5 00000006  r6 f49eb534  r7 0000010c
    r8 ffa41c68  r9 e691a9ec  sl ffffffff  fp e691a9a0
    ip 0000000b  sp ffa41bb8  lr f297c4c7  pc f297ed30  cpsr 600f0010
backtrace:
    #00 pc 0004ad30  /system/lib/libc.so (tgkill+12)
    #01 pc 000484c3  /system/lib/libc.so (pthread_kill+34)
    #02 pc 0001dd99  /system/lib/libc.so (raise+10)
    #03 pc 00019521  /system/lib/libc.so (__libc_android_abort+34)
    #04 pc 00017160  /system/lib/libc.so (abort+4)
    #05 pc 0001bd97  /system/lib/libc.so (__libc_fatal+22)
    #06 pc 000491e7  /system/lib/libc.so (__stack_chk_fail+6)
    #07 pc 0001a707  /system/lib/libc.so (epoll_pwait+82)
Lost connection to device.

Hope it is useful.
Regards

**Comment by Goddchen** [comment]
A nice explanation on the "stack corruption detection" issue can be found here: https://stackoverflow.com/a/30172297/373138

It doesn't really seem like there is much we can do 😢 If you have any ideas, feel free to re-open this issue.
